//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Example.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InputMatrixes", Namespace="http://schemas.datacontract.org/2004/07/WcfCalculationLib")]
    [System.SerializableAttribute()]
    public partial class InputMatrixes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] Mass_aField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] Mass_a {
            get {
                return this.Mass_aField;
            }
            set {
                if ((object.ReferenceEquals(this.Mass_aField, value) != true)) {
                    this.Mass_aField = value;
                    this.RaisePropertyChanged("Mass_a");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OutputMatrixes", Namespace="http://schemas.datacontract.org/2004/07/WcfCalculationLib")]
    [System.SerializableAttribute()]
    public partial class OutputMatrixes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] Mass_summField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] Mass_summ {
            get {
                return this.Mass_summField;
            }
            set {
                if ((object.ReferenceEquals(this.Mass_summField, value) != true)) {
                    this.Mass_summField = value;
                    this.RaisePropertyChanged("Mass_summ");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICaclcService")]
    public interface ICaclcService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaclcService/SumMatrixes", ReplyAction="http://tempuri.org/ICaclcService/SumMatrixesResponse")]
        WCF_Example.ServiceReference1.OutputMatrixes SumMatrixes(WCF_Example.ServiceReference1.InputMatrixes inputMatrixes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICaclcService/SumMatrixes", ReplyAction="http://tempuri.org/ICaclcService/SumMatrixesResponse")]
        System.Threading.Tasks.Task<WCF_Example.ServiceReference1.OutputMatrixes> SumMatrixesAsync(WCF_Example.ServiceReference1.InputMatrixes inputMatrixes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICaclcServiceChannel : WCF_Example.ServiceReference1.ICaclcService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CaclcServiceClient : System.ServiceModel.ClientBase<WCF_Example.ServiceReference1.ICaclcService>, WCF_Example.ServiceReference1.ICaclcService {
        
        public CaclcServiceClient() {
        }
        
        public CaclcServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CaclcServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CaclcServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CaclcServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF_Example.ServiceReference1.OutputMatrixes SumMatrixes(WCF_Example.ServiceReference1.InputMatrixes inputMatrixes) {
            return base.Channel.SumMatrixes(inputMatrixes);
        }
        
        public System.Threading.Tasks.Task<WCF_Example.ServiceReference1.OutputMatrixes> SumMatrixesAsync(WCF_Example.ServiceReference1.InputMatrixes inputMatrixes) {
            return base.Channel.SumMatrixesAsync(inputMatrixes);
        }
    }
}
